### PR TITLE
fix: fix issue in copy_to_directory where root_path is the full path of a directory input

### PR DESCRIPTION
**Pull request by tkoolen-bdi**
Hi @alexeagle, @gregmagolan :wave:. This adds a test case that is currently failing, but used to pass. See https://github.com/tkoolen-bdi/bazel-lib/tree/tkoolen/root-paths-glob-test-0.2.7 for the same test rebased onto v0.2.7, where it passes. We depend on the behavior in 0.2.7, which I think is what one would expect.

### CODE REVIEW

**Comment by gregmagolan** [comment]
Found the issue. Thanks for the repro. I'll push the fix to this PR and merge it in.

**Review by gregmagolan — APPROVED** [review]
🌮

**Comment by gregmagolan** [comment]
I cut a 1.10.1 release that will include the fix

**Comment by tkoolen-bdi** [comment]
Thanks for the quick fix!

**Pull request merged**
