### PR TITLE
build: add a presubmit.yml file for bazel buildkite ci

### PR DESCRIPTION
**Pull request by kormide**
@alexeagle 

Addresses https://github.com/bazelbuild/continuous-integration/issues/1313

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
oops, the filename was misspelled :)

**Comment by kormide** [comment]
> oops, the filename was misspelled :)

😵

**Comment by alexeagle** [comment]
cool now we get a legit failure https://buildkite.com/bazel/bazel-lib/builds/4

**Comment by kormide** [comment]
After the buildifier fixes, it looks like I just need a Windows implementation for write_source_files.

**Pull request merged**
