### PR TITLE
doc: update stamping.bzl making executable chmod

### PR DESCRIPTION
**Pull request by f0rmiga**

### CODE REVIEW

**Comment by cgrindel** [comment]
@f0rmiga If this is WIP, can we convert this PR to a draft so that it does not appear in our triage lists?

**Comment by f0rmiga** [comment]
@cgrindel what makes you think this is WIP?

**Comment by kormide** [comment]
This is failing because the generated docs need to be updated with `bazel run //docs:update`.

**Comment by f0rmiga** [comment]
Ah, thanks. I didn't notice CI was red.

**Review by kormide — APPROVED** [review]

**Pull request merged**
