### PR TITLE
feat: mtree_spec now supports symlinks

### PR DESCRIPTION
**Pull request by manuelnaranjo**
Changing mtree_spec so it can honor symlinks, if the target is a directory then the symlink will be to the directory, we don't need to expand those directories to make sure we follow the structure as expected.

From [issue 603](https://github.com/aspect-build/bazel-lib/issues/603) I could tell the support wasn't available, in the case of our internal Perl rules we rely heavily on symlinks to speed up times and files lookup, so not having the feature was making it harder for us to adopt rules_oci.

After researching the repo and some trialing I came with an implementation following the conventions of the repo that honors symlinks.

### Changes are visible to end-users: yes

- Searched for relevant documentation and updated as needed: yes
- Breaking change (forces users to change their own code or config): no
- Suggested release notes appear below: no

### Test plan

- Manual testing; please provide instructions so we can reproduce: have a binary that provide symlinks, the call to mtree_spec should have type=link entries with link= relative path to the target file, we did our tests again Bazel 6.5

### CODE REVIEW

**Comment by thesayyn** [comment]
Sorry, this doesn't work at all with `ctx.actions.symlink` and `ctx.actions.declare_symlink`. We actually need a runtime tool similar to js_image_layer to detect symlinks and apply corrections to mtree.

**Comment by manuelnaranjo** [comment]
@thesayyn shall we close it then?

**Comment by thesayyn** [comment]
> @thesayyn shall we close it then?

Yes

**Comment by thesayyn** [comment]
Closing this.

**Pull request closed without merging**
