### PR TITLE
docs: add a note about excluding from linters/formatters

### PR DESCRIPTION
**Pull request by Aghassi**
As discussed online, adding a note to the docgen about linting/formatting

### CODE REVIEW

**Review by gregmagolan — APPROVED** [review]
🙏 @Aghassi

**Review by gregmagolan — CHANGES_REQUESTED** [review]
Just have to run re-generate doc markdown files `bazel run //docs:update` to green it up

**Comment by Aghassi** [comment]
@gregmagolan you got it :)

**Review by gregmagolan — APPROVED** [review]
🙏

**Pull request merged**
