### PR TITLE
fix: hermetic bsdtar linux toolchain

### PR DESCRIPTION
**Pull request by thesayyn**
Now that linux toolchain for bsdtar linux_{amd64,arm64} includes all the libraries, every feature of it should work independently from host.

### Type of change

- Bug fix (change which fixes an issue)

### Test plan

- Covered by existing test cases

### CODE REVIEW

**Review by alexeagle — COMMENTED** [review]
I guess it should be a draft until we have a way to generate the file?

**Comment by alexeagle** [comment]
@thesayyn now that we also fetch the correct libc, is there anything remaining that's non-hermetic?

**Comment by betaboon** [comment]
i think the approach of using the ftp-urls here is very error-prone.
e.g. `https://ftp.debian.org/debian/pool/main/g/glibc/libc6_2.36-9+deb12u1_amd64.deb` already returns 404 today.

similar discussion in https://github.com/bazel-contrib/rules_oci/issues/375

**Comment by thesayyn** [comment]
> i think the approach of using the ftp-urls here is very error-prone. e.g. `https://ftp.debian.org/debian/pool/main/g/glibc/libc6_2.36-9+deb12u1_amd64.deb` already returns 404 today.
> 
> similar discussion in [bazel-contrib/rules_oci#375](https://github.com/bazel-contrib/rules_oci/issues/375)

yeah, that's why I abandoned this approach.

**Comment by betaboon** [comment]
> > i think the approach of using the ftp-urls here is very error-prone. e.g. `https://ftp.debian.org/debian/pool/main/g/glibc/libc6_2.36-9+deb12u1_amd64.deb` already returns 404 today.
> > similar discussion in [bazel-contrib/rules_oci#375](https://github.com/bazel-contrib/rules_oci/issues/375)
> 
> yeah, that's why I abandoned this approach.

ah lol. sorry didn't put your username in this PR and the other issue together :facepalm:

**Comment by thesayyn** [comment]
> @thesayyn now that we also fetch the correct libc, is there anything remaining that's non-hermetic?

This is not gonna work due to rolling updates trait of debian repos

**Comment by alexeagle** [comment]
I posted to bazel slack #general channel to see if anyone has a great answer for stable `.deb` fetches across the bazel ecosystem

**Comment by alexeagle** [comment]
replaced by https://github.com/aspect-build/bazel-lib/pull/804

**Pull request closed without merging**
