### PR TITLE
yq: allow any filename in srcs

### PR DESCRIPTION
**Pull request by pjjw**
we have a number of files in our repository that are yaml, despite not having a .yaml suffix in their filename, and this filter prevents us from using the yq rule on them.

---

### Type of change

- New feature or functionality (change which adds functionality)

### Test plan

- Covered by existing test cases

### CODE REVIEW

**Comment by kormide** [comment]
I think that we automatically set some `yq` flags based on the file types seen in `srcs`. See https://github.com/aspect-build/bazel-lib/blob/main/lib/yq.bzl#L165.

It would be great if you could add some tests for different input types but without extensions to test that nothing broke there.

**Comment by kormide** [comment]
> @kormide sure, added for a smattering of test cases for yaml and json with different-than-expected file extensions. seems to work fine, PTAL and see if there's some combination i missed here.

Thanks. LGTM with a minor nit: can you remove the `.whatever`/`.dealerschoice` extensions since the name of the test targets imply that they are testing no extension on the input file?

**Comment by pjjw** [comment]
how about i change the test names instead? really meant wrong or different- "no" in the sense of "no hints from the extension". naming!

**Review by kormide — APPROVED** [review]

**Comment by pjjw** [comment]
thanks! meant to circle back and fix that up.

**Comment by alexeagle** [comment]
Thanks for contributing @pjjw !!

**Pull request merged**
