### PR TITLE
feat: yq supports stamping

### LINKED ISSUE #223: Support stamping on yq rule
Useful for things like producing a package.json file that has the version field set from git tags.

### PR DESCRIPTION
**Pull request by malt3**
Fixes #223

---

### Type of change

- New feature or functionality (change which adds functionality)

**For changes visible to end-users**

- Relevant documentation has been updated
- Suggested release notes are provided below:
  ```
  Support stamping in yq rules
  ```

### Test plan

- New test cases added

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
Very nice, thank you!!

**Comment by alexeagle** [comment]
Test failure indicates a missing dep in a `bzl_library` rule - you can likely just `bazel run //:gazelle` to fix it.

**Comment by malt3** [comment]
> you can likely just bazel run //:gazelle to fix it.

Running gazelle yields a large number of changes that all seem to be unrelated to my PR.

I'm trying to understand what this means (related to stardoc):

```
File lib/paths.bzl imported '//lib/private:paths.bzl', yet lib/private/paths.bzl was not found, even at roots
```

**Comment by alexeagle** [comment]
Thanks, we just don't have a "gazelle up-to-date" CI check on this repo yet, so HEAD is out-of-date, sorry you tripped on that.

**Pull request merged**
