### PR TITLE
chore: improve the readme

### PR DESCRIPTION
**Pull request by kormide**
https://github.com/aspect-build/bazel-lib/issues/116

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
Take a look at my readme branch for ideas of things you'd like to reuse. I'm out of time for today 👍🏻

**Comment by kormide** [comment]
I tried to combine our approaches. I don't love the table headers but github markdown can't format tables without headers properly.

**Comment by kormide** [comment]
I added an alternative without tables in the second commit. Which do you prefer?

**Review by alexeagle — APPROVED** [review]
Yeah it's better without the table I think

**Pull request merged**
